[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd cliq-extension && npm ci --omit=dev"]

[phases.build]
cmds = ["cd cliq-extension && npm run validate || true"]

[start]
cmd = "cd cliq-extension && npm start"
